title: Логово автоматизатора
description: Блог о промышленной автоматизации, AggreGate, ПЛК и не только
lang: ru
theme: minima
baseurl: ""
url: "https://molchanov.lv"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

minima:
  skin: classic

header_pages:
  - files.md
  - about.md

author: Молчанов Л.В.
